// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fflsucsqhjjuozmfwpho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmbHN1Y3NxaGpqdW96bWZ3cGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTIwOTAsImV4cCI6MjA3NDM2ODA5MH0.NPc6bSfHFPLFzE0nz35e74oKOH4Gfg48M5AZuxcHZ44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);